name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: openstack/heat
          ref: 8c019d44f4a1e0c483d593f87dc82f0e5296d822 # stable/2025.2

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          image-name: heat
          build-contexts: heat=openstack/heat
          push: ${{ github.event_name != 'pull_request' }}
